[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# make `cargo run` start a GDB session
runner = "arm-none-eabi-gdb -q -x openocd.gdb"

[build]
# default compilation targets
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)